import json
import sys
import textwrap

def main():
    input_file = sys.argv[1]
    try:
        output_file = sys.argv[2]
    except IndexError:
        output_file = None

    with open(input_file) as f:
        input_map = json.load(f)
        print(input_map)

    print(sys.argv)

    file = textwrap.dedent(
        f'''\
        /* This file was automatically generated by 'gen_chordmap.py' */

        #include "../../lib/chordmap.h"
        x
        {input_map}
        '''
    )

    if output_file:
        with open(output_file, "w") as f:
            f.write(file)

    with open("C://mch_out.txt", "w") as f:
        f.write(file)


if __name__ == '__main__':
    main()
