''' Copyright 2025 Kim Hollstein (WiggelMc)
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
'''

from dataclasses import dataclass
from pathlib import Path
from string import Template
import textwrap

gen_disclaimer = '''\
/*
 * This file was automatically generated by 'gen_chordmap.py'.
 * Any changes will be overridden, when the chordmap is recompiled.
 */
'''

comment = f'/* /{"TEXT"} */'


def nl(indent: int):
    return '\n' + ' ' * 4 * indent


def create_gen_header(name: str, author: str):
    return (
        gen_disclaimer
        + f'{nl(0)}// {"chordmap": <10}: {name}'
        + f'{nl(0)}// {"author": <10}: {author}'
    )


@dataclass
class GenerationOutput:
    chordmap_c: str
    chordmap_data_h: str


def generate_code() -> GenerationOutput:
    dir_path = Path(__file__).parent.resolve()

    chordmap_c_template = dir_path.joinpath(
        'chordmap.c.template'
    ).read_text()
    chordmap_data_h_template = dir_path.joinpath(
        'chordmap_data.h.template'
    ).read_text()

    substitutions = {
        'gen_header': create_gen_header('default', 'WiggelMc'),
        'header_lines': ''.join(
            f'{nl(0)}{l}'
            for l in [
                "#include \"keymap_german.h\"",
                "//#include \"keymap_us_international.h\""
            ]
        ),
        'key_prefix': 'DE',
        'key_amount': '10',
        'chord_definitions': ''.join(
            f'{nl(1)}/* {c} */ [0x{i:04X}] = {k},{f" // {m}" if m is not None else ""}' for i, c, k, m in [(1, '00000 00000 L-', 'KC_RESERVED', '+S'), (2, '00000 01100 L1', 'KEY(A)', None)]
        ),
        'dk_mapping': ''.join(
            (f'{nl(1)}[0x{i:04X}] = {{ /* {n} */'
             + ''.join(f'{nl(2)}[0x{i:01X}] = {e},'
                       for i, e in reversed(list(enumerate(m)))
                       )
             + f'{nl(1)}}},'
             ) for i, n, m in [(1, 'Trainer Mode', ['KC_0', 'KC_1', 'KC_2', 'KC_3', 'KC_4', 'KC_5', 'KC_6', 'KC_7', 'KC_8', 'KC_9']), (2, 'QWERTY Row 2', ['KC_P', 'KC_O', 'KC_I', 'KC_U', 'KC_Y', 'KC_T', 'KC_R', 'KC_E', 'KC_W', 'KC_Q'])]
        ),
        'input_uint8m_code': 'm7654 3210-',
        'input_uint8m_mod': ''.join(
            f'{nl(2)}|| IS_BIT_SET(chord, {n})' for n in [9]
        ),
        'input_uint8m_bits': ''.join(
            f'{nl(2)}| (IS_BIT_SET_F(chord, {n}) << {o})' for o, n in [(0, 1), (1, 2), (2, 3), (3, 4), (4, 5), (5, 6), (6, 7), (7, 8)]
        ),
        'input_uint9_code': '87654 3210-',
        'input_uint9_bits': ''.join(
            f'{nl(2)}| (IS_BIT_SET_F(chord, {n}) << {o})' for o, n in [(0, 1), (1, 2), (2, 3), (3, 4), (4, 5), (5, 6), (6, 7), (7, 8), (8, 9)]
        ),
        'reset_options': ''.join(
            f'{nl(1)}options->{n} = {d};' for i, n, d in [(1, 'tap_code_delay', 0), (2, 'tap_code_gap', 0)]
        ),
        'reset_option_switch': ''.join(
            f'{nl(2)}case 0x{i:04X}:{nl(3)}options->{n} = {d};{nl(3)}return true;' for i, n, d in [(1, 'tap_code_delay', 0), (2, 'tap_code_gap', 0)]
        ),
        'set_option_switch': ''.join(
            f'{nl(2)}case 0x{i:04X}:{nl(3)}options->{n} = value;{nl(3)}return true;' for i, n, d in [(1, 'tap_code_delay', 0), (2, 'tap_code_gap', 0)]
        ),
        'special_noop_check': ''.join(
            f'{nl(2)}|| MASK_CMP(chord, 0x{b:04X}, 0x{m:04X}) // {c}' for b, m, c in [(0b11111_11111, 0b11111_11111, '11111 11111'), (0b11111_00000, 0b11111_11111, '11111 00000'), (0b00000_11111, 0b11111_11111, '00000 11111')]
        ),
        'special_cancel_check': ''.join(
            f'{nl(2)}|| MASK_CMP(chord, 0x{b:04X}, 0x{m:04X}) // {c}' for b, m, c in [(0b00000_00001, 0b11111_11111, '00000 00001')]
        ),
        'special_zero_check': ''.join(
            f'{nl(2)}|| MASK_CMP(chord, 0x{b:04X}, 0x{m:04X}) // {c}' for b, m, c in [(0b00000_10001, 0b00000_11111, '----- 10001')]
        ),
        'trainer_dk_index': f'0x{1:04X}',
        'layer_size': f'0x{12:02X}',
        'layer_index': ''.join(f'0x{v:02X}, ' for v in [0, 1, 2, 3, 4]),
        'chord_mapping': ''.join(f'0x{v:04X}, ' for v in [0, 1, 2, 3, 4]),
        'chord_mods': ''.join(f'0x{v:02X}, ' for v in [0, 1, 2, 3, 4]),
        'dk_index_mapping': ''.join(f'0x{v:04X}, ' for v in [0, 1, 2, 3, 4]),
        'option_index_mapping': ''.join(
            f'0x{v:04X}, ' for v in [12, 1, 2, 3, 4]
        ),
    }

    return GenerationOutput(
        chordmap_c=Template(
            chordmap_c_template
        ).substitute(substitutions),
        chordmap_data_h=Template(
            chordmap_data_h_template
        ).substitute(substitutions),
    )
